[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "matplotlib>=3.1.3",
    "numpy>=1.18.1",
    "pyNastran>=1.3.2",
    "pytest",
    "pytest-cov"
]
build-backend = "setuptools.build_meta"