# .github/workflows/pythonpackage.yml
name: Python Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8 flake8-html
          flake8 src --format=html --htmldir=flake-report-${{ matrix.python-version }}

      - name: Test with pytest
        run: |
          pip install pytest pytest-cov
          pytest --doctest-modules --junitxml=junit/test-results-${{ matrix.python-version }}.xml --cov=nastran --cov-report=html

      - name: Upload results
        uses: actions/upload-artifact@v2
        with:
          name: pytest-results-${{ matrix.python-version }}
          path: |
            junit/test-results-${{ matrix.python-version }}.xml
            htmlcov
            flake-report-${{ matrix.python-version }}

        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
